[package]
name = "dao"
version = "0.0.1"
edition = "2024.beta"
# published-at = "0x11cb97125374872b6abb230ea850ee9f9a288f8fdc1f4106b551ea8462e7d734"

[dependencies]
# 👇 Usuń ręczną definicję Sui
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/devnet" }

[addresses]
dao = "0x0"

[dev-dependencies]

[dev-addresses]
